name: continuous-integration
on:
  push:
    branches: '*'
    paths: 
      - '**.ts'
      - '**.tsx'
      - '**.yml'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x,22.x]

    steps:
      - uses: actions/checkout@v3

      - name: 'Use Node ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install dependencies (with package-lock)'
        run: 'npm ci'

      - name: 'Build project'
        run: 'npm run build'

      - name: 'Run unit tests'
        run: 'npm run test'

      

      